# standard jekyll configuration

permalink: /posts/:title
pygments: true
exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

github:
  username: github/sarahjschultz